package io.github.elnix90.settings.ir.generators

import io.github.elnix90.settings.util.ClassIds.allStoresAnnotationClassId
import io.github.elnix90.settings.util.ClassIds.settingsStoreAnnotationClassId
import io.github.elnix90.settings.util.ClassIds.settingsStoreClassId
import org.jetbrains.kotlin.backend.common.extensions.FirIncompatiblePluginAPI
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.ir.IrElement
import org.jetbrains.kotlin.ir.ObsoleteDescriptorBasedAPI
import org.jetbrains.kotlin.ir.UNDEFINED_OFFSET
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.IrField
import org.jetbrains.kotlin.ir.declarations.IrModuleFragment
import org.jetbrains.kotlin.ir.declarations.IrProperty
import org.jetbrains.kotlin.ir.declarations.createExpressionBody
import org.jetbrains.kotlin.ir.expressions.IrExpression
import org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrGetObjectValueImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrVarargImpl
import org.jetbrains.kotlin.ir.symbols.IrSimpleFunctionSymbol
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.types.impl.IrSimpleTypeImpl
import org.jetbrains.kotlin.ir.types.impl.IrStarProjectionImpl
import org.jetbrains.kotlin.ir.util.defaultType
import org.jetbrains.kotlin.ir.util.hasAnnotation
import org.jetbrains.kotlin.ir.util.isVararg
import org.jetbrains.kotlin.ir.visitors.IrVisitorVoid
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name

/**
 * IR transformer responsible for completing the implementation of the synthetic
 * `ALL` property generated by the FIR phase for classes annotated with `@SettingsStore`.
 *
 * The FIR extension only declares the property:
 *
 * ```
 * override val ALL: List<SettingObject<*, *>>
 * ```
 *
 * but does not provide its value. This transformer fills the backing field
 * initializer during IR generation.
 *
 * For every `@SettingsStore` class:
 *
 * 1. Finds the generated `ALL` property.
 * 2. Collects every property annotated with `@SettingKey`.
 * 3. Creates IR field accesses for each setting property.
 * 4. Builds a call to `kotlin.collections.listOf(vararg T)`.
 * 5. Packs all setting references into an `IrVarargImpl`.
 * 6. Assigns the resulting `listOf(...)` call as the initializer of the
 *    generated `ALL` backing field.
 *
 * This allows users to write:
 *
 * ```
 * @SettingsStore
 * object MyStore : MapSettingsStore(...) {
 *     @SettingKey val settingA = ...
 *     @SettingKey val settingB = ...
 * }
 * ```
 *
 * while the compiler effectively generates:
 *
 * ```
 * override val ALL = listOf(
 *     settingA,
 *     settingB
 * )
 * ```
 *
 * without requiring any manual declaration from the user.
 */
@OptIn(UnsafeDuringIrConstructionAPI::class)
internal class AllStoresGenerator(
    private val ctx: IrPluginContext
) {
    /**
     * Fills the AllStores value with the set of all the stores marked by `@SettingsStore`
     * The structure is similar to the `@SettingKey` resolution in [io.github.elnix90.settings.ir.transformers.SettingKeyTransformer]
     */
    @OptIn(FirIncompatiblePluginAPI::class, ObsoleteDescriptorBasedAPI::class)
    fun generateAllStorePropertyBody(
        module: IrModuleFragment
    ) {
        val stores: Set<IrClass> = collectStores(module)

        val allStoresField: IrField = module
            .files
            .flatMap { it.declarations }
            .filterIsInstance<IrProperty>()
            .firstOrNull {
                it.hasAnnotation(allStoresAnnotationClassId)
            }
            ?.backingField
            ?: return

        val args: Set<IrExpression> = stores.mapTo(mutableSetOf()) { store ->
            IrGetObjectValueImpl(
                startOffset = store.startOffset,
                endOffset = store.endOffset,
                type = store.defaultType,
                symbol = store.symbol
            )
        }

        val setOfSymbol: IrSimpleFunctionSymbol = ctx
            .referenceFunctions(
                CallableId(
                    FqName("kotlin.collections"),
                    Name.identifier("setOf")
                )
            ).first {
                it.owner.parameters.singleOrNull()?.isVararg == true
            }


        val call = IrCallImpl(
            startOffset = UNDEFINED_OFFSET,
            endOffset = UNDEFINED_OFFSET,
            type = allStoresField.type,
            origin = null,
            symbol = setOfSymbol,
            superQualifierSymbol = null
        )

        val settingsStoreClass =
            ctx.referenceClass(settingsStoreClassId)
                ?: error("SettingsStore not found")

        val storeType = IrSimpleTypeImpl(
            classifier = settingsStoreClass,
            hasQuestionMark = false,
            arguments = listOf(
                IrStarProjectionImpl,
                IrStarProjectionImpl
            ),
            annotations = emptyList()
        )

        val varargParameter = setOfSymbol.owner.parameters.single()

        val vararg = IrVarargImpl(
            startOffset = UNDEFINED_OFFSET,
            endOffset = UNDEFINED_OFFSET,
            type = varargParameter.type,
            varargElementType = storeType,
            elements = args.toList()
        )

        // THIS IS NEEDED!! otherwise the resolved type doesn't work and everything's messed up
        call.typeArguments[0] = storeType
        call.arguments[0] = vararg

        allStoresField.initializer = ctx.irFactory.createExpressionBody(call)
    }


    /**
     * Kinda like the other transformers, but as an anonymous object, that simply lists all the stores and return a list of them
     */
    @OptIn(UnsafeDuringIrConstructionAPI::class)
    private fun collectStores(
        module: IrModuleFragment
    ): Set<IrClass> {
        val stores = mutableSetOf<IrClass>()

        module.accept(object : IrVisitorVoid() {

            override fun visitElement(element: IrElement) {
                element.acceptChildren(this, null)
            }

            override fun visitClass(declaration: IrClass) {
                if (declaration.hasAnnotation(settingsStoreAnnotationClassId)) {
                    stores += declaration
                }

                super.visitClass(declaration)
            }
        }, null)

        return stores
    }
}