package io.github.elnix90.settings.ir

import org.jetbrains.kotlin.backend.common.extensions.FirIncompatiblePluginAPI
import org.jetbrains.kotlin.backend.common.extensions.IrPluginContext
import org.jetbrains.kotlin.ir.IrStatement
import org.jetbrains.kotlin.ir.ObsoleteDescriptorBasedAPI
import org.jetbrains.kotlin.ir.declarations.IrClass
import org.jetbrains.kotlin.ir.declarations.createExpressionBody
import org.jetbrains.kotlin.ir.expressions.impl.IrCallImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrGetFieldImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrGetValueImpl
import org.jetbrains.kotlin.ir.expressions.impl.IrVarargImpl
import org.jetbrains.kotlin.ir.symbols.UnsafeDuringIrConstructionAPI
import org.jetbrains.kotlin.ir.util.hasAnnotation
import org.jetbrains.kotlin.ir.util.isVararg
import org.jetbrains.kotlin.ir.util.properties
import org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid
import org.jetbrains.kotlin.name.CallableId
import org.jetbrains.kotlin.name.FqName
import org.jetbrains.kotlin.name.Name

/**
 * IR transformer responsible for completing the implementation of the synthetic
 * `ALL` property generated by the FIR phase for classes annotated with `@SettingStore`.
 *
 * The FIR extension only declares the property:
 *
 * ```
 * override val ALL: List<SettingObject<*, *>>
 * ```
 *
 * but does not provide its value. This transformer fills the backing field
 * initializer during IR generation.
 *
 * For every `@SettingStore` class:
 *
 * 1. Finds the generated `ALL` property.
 * 2. Collects every property annotated with `@SettingKey`.
 * 3. Creates IR field accesses for each setting property.
 * 4. Builds a call to `kotlin.collections.listOf(vararg T)`.
 * 5. Packs all setting references into an `IrVarargImpl`.
 * 6. Assigns the resulting `listOf(...)` call as the initializer of the
 *    generated `ALL` backing field.
 *
 * This allows users to write:
 *
 * ```
 * @SettingStore
 * object MyStore : MapSettingsStore(...) {
 *     @SettingKey val settingA = ...
 *     @SettingKey val settingB = ...
 * }
 * ```
 *
 * while the compiler effectively generates:
 *
 * ```
 * override val ALL = listOf(
 *     settingA,
 *     settingB
 * )
 * ```
 *
 * without requiring any manual declaration from the user.
 */
@OptIn(UnsafeDuringIrConstructionAPI::class)
class SettingStoreTransformer(
    private val context: IrPluginContext,
) : IrElementTransformerVoid() {

    override fun visitClass(declaration: IrClass): IrStatement {
        if (declaration.hasAnnotation(settingStoreClassId)) {
            generateAllPropertyBody(declaration)
        }
        return super.visitClass(declaration)
    }

    @OptIn(FirIncompatiblePluginAPI::class, ObsoleteDescriptorBasedAPI::class)
    private fun generateAllPropertyBody(storeClass: IrClass) {

        val allProperty = storeClass.properties.firstOrNull {
            it.name.asString() == "ALL"
        } ?: return


        val settingKeyProperties = storeClass.properties
            .filter { prop -> context.hasSettingKey(prop) }
            .toList()


        if (settingKeyProperties.isEmpty()) return


        val listOfSymbol = context
            .referenceFunctions(
                CallableId(FqName("kotlin.collections"), Name.identifier("listOf"))
            )
            .firstOrNull {
                val param = it.owner.parameters
                param.size == 1 && param[0].isVararg
            }
            ?: error("Cannot find listOf(vararg)")


        val thisReceiver = IrGetValueImpl(
            startOffset = storeClass.startOffset,
            endOffset = storeClass.endOffset,
            type = storeClass.thisReceiver!!.type,
            symbol = storeClass.thisReceiver!!.symbol
        )

        val args = settingKeyProperties.map { prop ->
            val field = prop.backingField ?: error("No backing field for ${prop.name}")

            IrGetFieldImpl(
                startOffset = storeClass.startOffset,
                endOffset = storeClass.endOffset,
                symbol = field.symbol,
                type = field.type,
                receiver = thisReceiver,
                origin = null,
                superQualifierSymbol = null
            )
        }

        val call = IrCallImpl(
            startOffset = storeClass.startOffset,
            endOffset = storeClass.endOffset,
            type = listOfSymbol.owner.returnType,
            origin = null,
            symbol = listOfSymbol,
            superQualifierSymbol = null
        )


        val vararg = IrVarargImpl(
            startOffset = storeClass.startOffset,
            endOffset = storeClass.endOffset,
            type = listOfSymbol.owner.parameters[0].type,
            varargElementType = listOfSymbol.owner.parameters[0].type,
            elements = args.toList()
        )

        call.arguments[0] = vararg

        allProperty.backingField?.initializer =
            context.irFactory.createExpressionBody(call)
    }
}